# Copyright 2018-2022 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes and configures the Datadog Agent"
  homepage = "https://github.com/paketo-buildpacks/datadog"
  id = "paketo-buildpacks/datadog"
  keywords = ["java"]
  name = "Paketo Buildpack for Datadog"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/maven/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "README.md", "bin/build", "bin/detect", "bin/main", "bin/helper", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "whether to contribute the Datadog trace agent"
    name = "BP_DATADOG_ENABLED"

  [[metadata.configurations]]
    default = "false"
    description = "whether to disable the Datadog trace agent (non native-image Java applications only!)"
    launch = true
    name = "BPL_DATADOG_DISABLED"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:datadoghq:java-agent:1.28.0:*:*:*:*:*:*:*"]
    id = "datadog-agent-java"
    name = "Datadog Java Agent"
    purl = "pkg:generic/datadog-java-agent@1.28.0?arch=amd64"
    sha256 = "d3c8248c4a038fa999c33194d9ce9f905f2b59af6073408ded46cec752e657ea"
    source = "https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/1.28.0/dd-java-agent-1.28.0-sources.jar"
    source-sha256 = "75c936ff37ce51e31c11255c35ff9d833c42b6fa27477eb630317426f549210a"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/1.28.0/dd-java-agent-1.28.0.jar"
    version = "1.28.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/DataDog/dd-trace-java/blob/master/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:datadoghq:nodejs-agent:5.0.0:*:*:*:*:*:*:*"]
    id = "datadog-agent-nodejs"
    name = "Datadog NodeJS Agent"
    purl = "pkg:generic/datadog-nodejs-agent@5.0.0?arch=amd64"
    sha256 = "2acfa9a85c5ea7f7e7ae3863820339c05d490116c28e9de8e7978fc82c38eefc"
    source = "https://registry.npmjs.org/dd-trace/-/dd-trace-5.0.0.tgz"
    source-sha256 = "2acfa9a85c5ea7f7e7ae3863820339c05d490116c28e9de8e7978fc82c38eefc"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://registry.npmjs.org/dd-trace/-/dd-trace-5.0.0.tgz"
    version = "5.0.0"

    [[metadata.dependencies.licenses]]
      type = "BSD-3-Clause"
      uri = "https://github.com/DataDog/dd-trace-js/blob/master/LICENSE.BSD3"

    [[metadata.dependencies.licenses]]
      type = "Apache-2.0"
      uri = "https://github.com/DataDog/dd-trace-js/blob/master/LICENSE.Apache"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
